# Generated by Django 4.2.5 on 2023-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[('Part 1', 1), ('Part 2', 2), ('Part 3', 3), ('Part 3', 4)])),
                ('problem', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[('Part 1', 1), ('Part 2', 2), ('Part 3', 3), ('Part 3', 4)])),
                ('problem', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
