# Generated by Django 4.2.5 on 2023-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_writing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaking',
            name='type',
            field=models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')]),
        ),
        migrations.AlterField(
            model_name='writing',
            name='type',
            field=models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')]),
        ),
    ]
